### ISSUE TITLE
License

### ISSUE THREAD

**Issue by deltabeard** [gregtour/gameboy#1]
Hello,
I was wondering what license (if at all) this project is under?

Nice work,
Mahyar

**Comment by gregtour** [comment]
The software is provided under the Creative Commons license. The software is free to use for any purpose and there is no need to include a notice.

**Comment by davecom** [comment]
Please include an actual license file (even if it's just to say it's public domain). Without one, I'm hesitant to reuse your code (thinking of reusing the bitmap font rendering).
