### ISSUE TITLE
Reducing scale

### ISSUE THREAD

**Issue by deltabeard** [gregtour/gameboy#3]
Currently by default, the output video is scaled by a factor of 4 as shown below.
![gameboy-c-x4](https://cloud.githubusercontent.com/assets/3747104/8533647/527bfea4-242e-11e5-9021-d20ed467a69e.png)

I'm currently having trouble reducing the scale, and also fixing the wrapping as shown in the image (which was caused when trying to remove the black border). I'm hoping to eventually get a 160x144 video output with no black border within the window and no wrapping.

I was wondering if you could point me in the right direction?

**Comment by gregtour** [comment]
Sure.

I noticed you're building on a platform other than windows, so if you look at platform.c or wherever main() is there is a section of code for copying the framebuffer into SDL. The emulator uses a 32-bit 160x144 buffer for storing the screen image. That's stored in fb.

I wanted to use the emulator fullscreen so I picked a normal resolution and used letterboxing, but if you're going to keep the aspect ratio or stretch to fill the screen, than you can use different code to blit the frame to SDL. You can also use a totally different library to set up your window context or draw. For example on Windows, you could eliminate the use of SDL by rendering pixel data to a window using GDI.

When setting up your window you have:

``` C
screen = SDL_SetVideoMode(SCR_WIDTH + 100, SCR_HEIGHT + 100, 32, SDL_HWSURFACE | SDL_DOUBLEBUF /*| SDL_FULLSCREEN*/);
    SDL_WM_SetCaption("GameBoy", 0);
```

You should eliminate the + 100 adjustment and just use SCR_WIDTH and SCR_HEIGHT for the window size.

Here is a snippet of code that should render to a scaled surface. This is what the code originally looked like as well:

``` C
            // copy framebuffer
            u32* s = (u32*)screen->pixels;
            for (int y = 0; y < SCR_HEIGHT; y++)
                {
                for (int x = 0; x < SCR_WIDTH; x++)
                    *(s + x) = fb[y/4][x/4];
                s += screen->pitch/4;
                }
```

This assumes that SCR_WIDTH and SCR_HEIGHT are four times LCD_WIDTH and LCD_HEIGHT. Something more reliable that would scale (without filtering) to an arbitrary size would be:

``` C
                    *(s + x) = fb[y*LCD_HEIGHT/SCR_HEIGHT][x*LCD_WIDTH/SCR_WIDTH];
```

There is a lot more information on the resources I used and limitations I encountered that I should include with the project. There is also some cleaning up I have to do as I noticed from your changes, which I might pull back.

Thanks for your interest!

**Comment by deltabeard** [comment]
Thanks a lot for the reply! I'll have a look at the code now and make the changes that you have suggested.
This is a really nice project. It doesn't require many libraries at all, only uses C programming language (unlike others which use C++ and python), and produces a binary that is very small. I'm only a beginner in C, but in the long term, I would like to port this emulator to a small ARM chip which also means reducing the CPU usage of the emulator (which currently uses more than gambatte) and RAM usage.

Edit: Excellent! The code you provided fixed the issues I was having before.

**Comment by gregtour** [comment]
Mmkay, sounds swell. I'd like to help if I can.

I hadn't really considered performance (or memory usage) to be a concern just because I've been using this emulator on a PC and it's emulating 4MHz hardware with quite a bit of power and memory, but it would be fun to optimize it. 

You mention targeting ARM, which may require some assembly of its own, but there are some interesting ideas for dynamic recompilation or re-structuring the program to gain performance. Ideally, it would be faster than gambatte ;)

Cheers.
