### ISSUE TITLE
Fix inconsistent timing on Windows.

### ISSUE THREAD

**Issue by gregtour** [gregtour/gameboy#6]
The Win32 build provides an estimate of the FPS of the emulator, however, it has very little to do with the timing value used in the program. Additionally, frameskip has not been implemented.

**Comment by gregtour** [comment]
There still seem to be some issues with frame timing on the WM_PAINT event, possibly related to using Windows 7. Remedies might be to use Direct2D (possibly deprecated) or OpenGL for rendering, whichever has better support on Windows machines. In the latest revision I decided to drop using windows timers and instead use the millisecond clock.

**Comment by deltabeard** [comment]
Using OpenGL would ensure support on Linux. I think Direct2D (or at least Direct3D) API is Windows only.
